# -*- coding: utf-8 -*-
"""GeoAI_Ship_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8CTcZyAVhZRziYZ8co2YaltHZkhdlEt

## **Ship Detection Using GeoAI**
This notebook utilizes GeoAI package to detect ships using pre-trained model.GeoAI is a powerful Python package for integrating artificial intelligence with geospatial data analysis and visualization You can find detailed information about GeoAI library here : https://opengeoai.org/

Install geoai package
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install geoai-py

"""Import libraries"""

import geoai

"""Access the data"""

# Mount Google Drive to get access to the data
from google.colab import drive
drive.mount("/content/drive")

# Provide path to the TIFF dataset
ortho_path = "/content/drive/MyDrive/AppDevelopment/BE_ORTHO_27032011_315140_56865_UTM31N.tif"

"""Visualise the data"""

import matplotlib.pyplot as plt
import rasterio
from rasterio.enums import Resampling

with rasterio.open(ortho_path) as src:
    scale = 4
    out_shape = (src.count, src.height // scale, src.width // scale)
    arr = src.read(out_shape=out_shape, resampling=Resampling.bilinear)

plt.figure(figsize=(12, 12))
plt.imshow(arr[:3].transpose(1, 2, 0) if arr.shape[0] >= 3 else arr[0], cmap="gray" if arr.shape[0]==1 else None)
plt.axis("off")
plt.show()

"""Initialize Ship Detection Model"""

detector = geoai.ShipDetector()

"""Generate masks"""

output_path = "ships_detected.tif"

masks_path = detector.generate_masks(
    ortho_path,
    output_path=output_path,
    confidence_threshold=0.5,
    mask_threshold=0.5,
    overlap=0.5,
    chip_size=(512, 512),
    batch_size=4,
)

"""Visualise the result"""

import rasterio
import matplotlib.pyplot as plt

with rasterio.open("ships_detected.tif") as src:
    mask_band = src.read(1)
    conf_band = src.read(2)

fig, axes = plt.subplots(1, 2, figsize=(16, 8))

axes[0].imshow(mask_band, cmap="gray")
axes[0].set_title(f"Ship mask — {(mask_band > 0).sum()} pixels")

im = axes[1].imshow(conf_band, cmap="viridis")
axes[1].set_title("Confidence")
plt.colorbar(im, ax=axes[1], fraction=0.046)

plt.tight_layout()
plt.show()

"""Vectorize the masks"""

gdf = detector.vectorize_masks(
    masks_path=output_path,
    output_path="ships_detected.geojson",
    confidence_threshold=0.8,
    min_object_area=5500,
    max_object_area=25000,
    n_workers=-1,
)

"""Visualise the vectorized masks"""

import rasterio
from rasterio.plot import show
from rasterio.enums import Resampling
import matplotlib.pyplot as plt

scale = 4

with rasterio.open(ortho_path) as src:
    out_shape = (src.count, src.height // scale, src.width // scale)
    arr = src.read(out_shape=out_shape, resampling=Resampling.bilinear)
    transform = src.transform * src.transform.scale(scale, scale)

fig, ax = plt.subplots(figsize=(15, 15))
show(arr, transform=transform, ax=ax)

gdf.plot(ax=ax, facecolor="none", edgecolor="red", linewidth=1.2)
ax.set_title(f"Detected ships: {len(gdf)}")
ax.axis("off")
plt.tight_layout()
plt.show()

"""Approach 2 : Downsampling the ortho imagery to 15cm"""

resampled_path = "ships_15cm.tif"

import os
import math
import rasterio
from rasterio.enums import Resampling

"""Resampling the image to 15cm"""

with rasterio.open(ortho_path) as src:
    if src.crs.is_geographic:
        lat = (src.bounds.top + src.bounds.bottom) / 2
        res_cm = src.res[0] * 111320 * math.cos(math.radians(lat)) * 100
    else:
        res_cm = src.res[0] * 100

    print(f"Resolution: {res_cm:.1f} cm/pixel")

# Compute scale factor to reach 15 cm/pixel
SCALE = res_cm / 15.0

# --- DIRECT RESAMPLING -
with rasterio.open(ortho_path) as src:
    new_w = int(src.width  * SCALE)
    new_h = int(src.height * SCALE)

    # Correct transform scaling
    xscale = src.width / new_w
    yscale = src.height / new_h
    new_transform = src.transform * rasterio.Affine.scale(xscale, yscale)

    data = src.read(
        out_shape=(src.count, new_h, new_w),
        resampling=Resampling.average,
    )

    profile = src.profile.copy()
    profile.update(
        width=new_w,
        height=new_h,
        transform=new_transform
    )

    with rasterio.open(resampled_path, "w", **profile) as dst:
        dst.write(data)

print(f"Resampled saved: {resampled_path}")

output_path_resampled = "ships_masks_15cm.tif"

"""Generate masks"""

masks_path_resampled = detector.generate_masks(
    resampled_path,
    output_path=output_path_resampled,
    confidence_threshold=0.5,
    mask_threshold=0.5,
    overlap=0.5,
    chip_size=(512, 512),
    batch_size=4,
)

"""Visualise the masks"""

import rasterio
import matplotlib.pyplot as plt

with rasterio.open(output_path_resampled) as src:
    mask_band = src.read(1)
    conf_band = src.read(2)

fig, axes = plt.subplots(1, 2, figsize=(16, 8))

axes[0].imshow(mask_band, cmap="gray")
axes[0].set_title(f"Ship mask — {(mask_band > 0).sum()} pixels")

im = axes[1].imshow(conf_band, cmap="viridis")
axes[1].set_title("Confidence")
plt.colorbar(im, ax=axes[1], fraction=0.046)

plt.tight_layout()
plt.show()

"""Vectorize the mask"""

gdf_masked = detector.vectorize_masks(
    output_path_resampled,
    output_path="ships_masks_resampled.geojson",
    confidence_threshold=0.8,
    min_object_area=100,
    max_object_size=100000,
)

print(type(gdf_masked))

# Check how many vertices each polygon has
for i, geom in enumerate(gdf_masked.geometry.head(5)):
    coords = list(geom.exterior.coords)
    print(f"Ship {i}: {len(coords)} vertices")

"""Visualise the result"""

import rasterio
from rasterio.plot import show
from rasterio.enums import Resampling
import matplotlib.pyplot as plt

scale = 4

with rasterio.open(ortho_path) as src:
    out_shape = (src.count, src.height // scale, src.width // scale)
    arr = src.read(out_shape=out_shape, resampling=Resampling.bilinear)
    transform = src.transform * src.transform.scale(scale, scale)

fig, ax = plt.subplots(figsize=(15, 15))
show(arr, transform=transform, ax=ax)

gdf_masked.plot(ax=ax, facecolor="none", edgecolor="red", linewidth=1.2)
ax.set_title(f"Detected ships: {len(gdf_masked)}")
ax.axis("off")
plt.tight_layout()
plt.show()

"""Calculate geometric properties"""

gdf_masked = geoai.add_geometric_properties(gdf_masked)
gdf_masked.head()

import geopandas as gpd

gdf_native = gpd.read_file("/content/ships_detected.geojson")
gdf_15cm = gpd.read_file("/content/ships_masks_resampled.geojson")

print(f"4.2cm detections: {len(gdf_native)}")
print(f"15cm detections: {len(gdf_15cm)}")

import shutil, os
dest_dir = "/content/drive/MyDrive/AppDevelopment/GeoAIoutputs"
os.makedirs(dest_dir, exist_ok=True)
for f in ["ships_15cm.tif", "ships_detected.geojson", "ships_detected.tif",
          "ships_masks_15cm.tif", "ships_masks_resampled.geojson"]:
    shutil.copy(f"/content/{f}", f"{dest_dir}/{f}")
print("Done")
